/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface HolyGrid {}
  interface HolyGridAttributes extends StencilHTMLAttributes {}

  interface MyComponent {
    'changeCadena': (nuevaCadena: string) => void;
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
    'onSendCadena'?: (event: CustomEvent) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'HolyGrid': Components.HolyGrid;
    'MyComponent': Components.MyComponent;
  }

  interface StencilIntrinsicElements {
    'holy-grid': Components.HolyGridAttributes;
    'my-component': Components.MyComponentAttributes;
  }


  interface HTMLHolyGridElement extends Components.HolyGrid, HTMLStencilElement {}
  var HTMLHolyGridElement: {
    prototype: HTMLHolyGridElement;
    new (): HTMLHolyGridElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLElementTagNameMap {
    'holy-grid': HTMLHolyGridElement
    'my-component': HTMLMyComponentElement
  }

  interface ElementTagNameMap {
    'holy-grid': HTMLHolyGridElement;
    'my-component': HTMLMyComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
